version: '3'

services:
  app:
    build:
      dockerfile: ./src/.docker/server/Dockerfile
      context: .
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8000:8000"
    working_dir: /app
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'timezone=Asia/Tokyo'

volumes:
  postgres_data:
